### ISSUE TITLE
TypeError: Can't index by type: <class 'NoneType'>; only int, string or slice

### ISSUE THREAD

**Issue by lionel-xie** [chagmgang/pysc2_rl#1]
**when i run CollectMineral(ppo)-->stata_group：**
        state = np.dstack((marine_map, mineral_map)).reshape(32*32*2)
**came out：**
E0330 17:18:23.828569 81116 _logging.py:54] close status: 16896
W0330 17:18:26.929746 81116 sc_process.py:200] Killing the process.
Traceback (most recent call last):
  File "E:/Anaconda/Lib/site-packages/pysc2/agents/pysc2_rl-master/CollectMineral(ppo)/CollectMineral.py", line 143, in <module>
    train()
  File "E:/Anaconda/Lib/site-packages/pysc2/agents/pysc2_rl-master/CollectMineral(ppo)/CollectMineral.py", line 71, in train
    state = obs2state(obs)
  File "E:\Anaconda\Lib\site-packages\pysc2\agents\pysc2_rl-master\CollectMineral(ppo)\state_group.py", line 33, in obs2state
    state = np.dstack((marine_map, mineral_map)).reshape(32*32*2)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\numpy\lib\shape_base.py", line 699, in dstack
    return _nx.concatenate([atleast_3d(_m) for _m in tup], 2)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\numpy\lib\shape_base.py", line 699, in <listcomp>
    return _nx.concatenate([atleast_3d(_m) for _m in tup], 2)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\numpy\core\shape_base.py", line 199, in atleast_3d
    result = ary[:,:, newaxis]
  File "E:\Anaconda\lib\site-packages\pysc2\lib\named_array.py", line 145, in __getitem__
    index = _get_index(obj, index)
  File "E:\Anaconda\lib\site-packages\pysc2\lib\named_array.py", line 207, in _get_index
    "Can't index by type: %s; only int, string or slice" % type(index))
TypeError: Can't index by type: <class 'NoneType'>; only int, string or slice

**Comment by xxd819240366** [comment]
why reshape->32*32*2? minimap size is 64*64,so why not reshape-->32*32*8?
